export class Bridge {

  // this is just a temporary example. will be replaced by api call 
  data_temp: object = {
    "0": {
      "Accession": "0",
      "Title": "test",
      "Location": "RO_BB1",
      "SubjectHeadings": "Food, Markets, Medicine",
      "Description": "Small glass bottle without a cap.",
      "Date": "1950s",
      "CreatedBy": "Glass Bottleworks",
      "Size": "2\"x6\"",
      "Condition": "Bad",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": "Broken at the neck of the bottle"
    },
    "2025.01.001": {
      "Accession": "2025.01.001",
      "Title": "Glass Bottle",
      "Location": "RO_BB1",
      "SubjectHeadings": "Food, Markets, Medicine",
      "Description": "Small glass bottle without a cap.",
      "Date": "1950s",
      "CreatedBy": "Glass Bottleworks",
      "Size": "2\"x6\"",
      "Condition": "Bad",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": "Broken at the neck of the bottle"
    },
    "oeo": {
      "Accession": "oeo",
      "Title": "Glass Bottle",
      "Location": "RO_BB1",
      "SubjectHeadings": "Food, Markets, Medicine",
      "Description": "Small glass bottle without a cap.",
      "Date": "1950s",
      "CreatedBy": "Glass Bottleworks",
      "Size": "2\"x6\"",
      "Condition": "Bad",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": "Broken at the neck of the bottle"
    },
    "2025.01.002": {
      "Accession": "2025.01.002",
      "Title": "Oral History - John Doe",
      "Location": "RO_BB1",
      "SubjectHeadings": "Oral History, Italian History",
      "Description": "Oral history recording",
      "Date": "May 22 1999",
      "CreatedBy": "Ybor City Museum Society",
      "Size": "30 minutes",
      "Condition": "Fair",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[pdf]",
      "Notes": "[mp3]"
    },
    "2025.01.003": {
      "Accession": "2025.01.003",
      "Title": "Handwritten Dairy of a Woman's Life",
      "Location": "RO_BB1",
      "SubjectHeadings": "Manuscript",
      "Description": "Women of Ybor, Spanish Culture",
      "Date": "Handwritten dairy from the years of 1910-1915 about her life, job, and marriage in Ybor.",
      "CreatedBy": "1910s",
      "Size": "Jane Doe",
      "Condition": "62 pgs",
      "Status": "Fair ",
      "DonatedBy": "Donated",
      "Acquisition": "Jane Doe",
      "Attachment": "[pdf]",
      "Notes": "[pdf]"
    },
    "2025.01.004": {
      "Accession": "2025.01.004",
      "Title": "Baseball Signed by Al Lopez",
      "Location": "RO_BB1",
      "SubjectHeadings": "Baseball in Tampa Bay, Al Lopez, Spanish History",
      "Description": "Baseball signed by major league player Al Lopez.",
      "Date": 1950,
      "CreatedBy": "Rawlings",
      "Size": "9\" circ.",
      "Condition": "Excellent",
      "Status": "Donated ",
      "DonatedBy": "Al Lopez",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.005": {
      "Accession": "2025.01.005",
      "Title": "Painting of Ybor Street",
      "Location": "RO_BB1",
      "SubjectHeadings": "Art, Painting, Ybor City Streets",
      "Description": "Acrylic painting of ybor city street.",
      "Date": "2010s",
      "CreatedBy": "Arnold Martinez",
      "Size": "10\"x5\"",
      "Condition": "Excellent",
      "Status": "Donated",
      "DonatedBy": "Arnold Martinez",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.006": {
      "Accession": "2025.01.006",
      "Title": "Wooden Cigar Mold",
      "Location": "RO_BB1",
      "SubjectHeadings": "Cigar Industry, Cuban Culture",
      "Description": "Tabletop cigar mold designed to fit 30 cigars",
      "Date": "Early 1900s",
      "CreatedBy": "Perfecto Garcia Bros.",
      "Size": "24\"x3\"",
      "Condition": "Fair ",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.007": {
      "Accession": "2025.01.007",
      "Title": "Spanish Madre\u00f1as",
      "Location": "RO_BB1",
      "SubjectHeadings": "Spanish Culture, Asturian Culture,\nShoes",
      "Description": "Wooden clog-like overshoes from Asturias Spain",
      "Date": "1930s",
      "CreatedBy": "N/A",
      "Size": "13\"",
      "Condition": "Good",
      "Status": "Donated",
      "DonatedBy": "N/A",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.008": {
      "Accession": "2025.01.008",
      "Title": "WPA Blueprints for House",
      "Location": "RO_BB1",
      "SubjectHeadings": "WPA, Architecture",
      "Description": "Two - story residence for Blueprints and Architecture notes from BB Architects",
      "Date": "May 25 1935",
      "CreatedBy": "BB Architects",
      "Size": "48\"'x24\"",
      "Condition": "Bad",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.009": {
      "Accession": "2025.01.009",
      "Title": "Centro Asturiano Membership Card Book",
      "Location": "RO_BB1",
      "SubjectHeadings": "Spanish Culture, Mutual Aid Societies",
      "Description": "Small booklet display a picture and the information of a Centro Asturiano member.",
      "Date": "1930s",
      "CreatedBy": "Centro Asturianp",
      "Size": "2\"x4\"",
      "Condition": "Poor",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": "Very delicate, binding fragile"
    },
    "2025.01.010": {
      "Accession": "2025.01.010",
      "Title": "2021 Annual Cigar Heritage Festival Poster",
      "Location": "RO_BB1",
      "SubjectHeadings": "Cigar Industry, Ybor City Festivals",
      "Description": "Medium sized poster to promote the 2021 Annual Cigar Heritage Festival",
      "Date": 2021,
      "CreatedBy": "Ybor City Museum Society, Cigar Heritage Festival",
      "Size": "18\"x24\"",
      "Condition": "Good",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.011": {
      "Accession": "2025.01.011",
      "Title": "Burgert Brothers photograph of women at work in the cigar industry",
      "Location": "RO_BB1",
      "SubjectHeadings": "Art & Artists, Cigar Industry, Burgert Brothers",
      "Description": "Black and white mage of three women working in an Ybor cityt cigar factory.",
      "Date": "1930s",
      "CreatedBy": "Burgert Bros Tampa",
      "Size": "8\" x 10\"",
      "Condition": "Good",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[jpeg]",
      "Notes": null
    },
    "2025.01.012": {
      "Accession": "2025.01.012",
      "Title": "Krewe of Ybor Recods",
      "Location": "RO_BB1",
      "SubjectHeadings": "Krewe, Ybor Culture",
      "Description": "Documents about membership information for the Krewe of Ybor",
      "Date": 2000,
      "CreatedBy": "Krewe of Ybor",
      "Size": "N/A",
      "Condition": "Fair",
      "Status": "Donated",
      "DonatedBy": "John Doe",
      "Acquisition": "[pdf]",
      "Attachment": "[pdf]",
      "Notes": null
    }
  };

  public data = new Map(Object.entries(this.data_temp));
  public list_of_keys = Array.from(this.data.keys());
  constructor() {
  }



}
